/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AfterMarketServicesRouteImport } from './routes/after-market-services'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SuperiorValueCreationRouteImport } from './routes/superior-value-creation'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsChemicalInjectionPackagesRouteImport } from './routes/solutions.chemical-injection-packages'
import { Route as SolutionsEngineeredSolutionsRouteImport } from './routes/solutions.engineered-solutions'
import { Route as SolutionsModularPackagesRouteImport } from './routes/solutions.modular-packages'
import { Route as SolutionsWellheadControlSystemsRouteImport } from './routes/solutions.wellhead-control-systems'
import { Route as SuperiorValueCreationIndexRouteImport } from './routes/superior-value-creation.index'
import { Route as SuperiorValueCreationEquipmentRentalRouteImport } from './routes/superior-value-creation.equipment-rental'
import { Route as SuperiorValueCreationFlushingRouteImport } from './routes/superior-value-creation.flushing'
import { Route as SuperiorValueCreationLongTermServiceAgreementRouteImport } from './routes/superior-value-creation.long-term-service-agreement'
import { Route as SuperiorValueCreationMaintenanceContractsRouteImport } from './routes/superior-value-creation.maintenance-contracts'
import { Route as SuperiorValueCreationPressureTestingRouteImport } from './routes/superior-value-creation.pressure-testing'
import { Route as SuperiorValueCreationProductTrainingRouteImport } from './routes/superior-value-creation.product-training'
import { Route as SuperiorValueCreationRefurbishmentsRecertificationRouteImport } from './routes/superior-value-creation.refurbishments-recertification'
import { Route as SolutionsEngineeredSolutionsIndexRouteImport } from './routes/solutions.engineered-solutions.index'
import { Route as SolutionsEngineeredSolutionsDraInjectionSystemsRouteImport } from './routes/solutions.engineered-solutions.dra-injection-systems'
import { Route as SolutionsEngineeredSolutionsHippsSystemsRouteImport } from './routes/solutions.engineered-solutions.hipps-systems'
import { Route as SolutionsEngineeredSolutionsLubeOilSystemsRouteImport } from './routes/solutions.engineered-solutions.lube-oil-systems'
import { Route as SolutionsEngineeredSolutionsMeteringSkidsRouteImport } from './routes/solutions.engineered-solutions.metering-skids'
import { Route as SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRouteImport } from './routes/solutions.engineered-solutions.nitrogen-generator-packages'
import { Route as SolutionsEngineeredSolutionsSurgeReliefSkidsRouteImport } from './routes/solutions.engineered-solutions.surge-relief-skids'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AfterMarketServicesRoute = AfterMarketServicesRouteImport.update({
  id: '/after-market-services',
  path: '/after-market-services',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperiorValueCreationRoute = SuperiorValueCreationRouteImport.update({
  id: '/superior-value-creation',
  path: '/superior-value-creation',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsChemicalInjectionPackagesRoute =
  SolutionsChemicalInjectionPackagesRouteImport.update({
    id: '/solutions/chemical-injection-packages',
    path: '/solutions/chemical-injection-packages',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsEngineeredSolutionsRoute =
  SolutionsEngineeredSolutionsRouteImport.update({
    id: '/solutions/engineered-solutions',
    path: '/solutions/engineered-solutions',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsModularPackagesRoute =
  SolutionsModularPackagesRouteImport.update({
    id: '/solutions/modular-packages',
    path: '/solutions/modular-packages',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsWellheadControlSystemsRoute =
  SolutionsWellheadControlSystemsRouteImport.update({
    id: '/solutions/wellhead-control-systems',
    path: '/solutions/wellhead-control-systems',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperiorValueCreationIndexRoute =
  SuperiorValueCreationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SuperiorValueCreationRoute,
  } as any)
const SuperiorValueCreationEquipmentRentalRoute =
  SuperiorValueCreationEquipmentRentalRouteImport.update({
    id: '/equipment-rental',
    path: '/equipment-rental',
    getParentRoute: () => SuperiorValueCreationRoute,
  } as any)
const SuperiorValueCreationFlushingRoute =
  SuperiorValueCreationFlushingRouteImport.update({
    id: '/flushing',
    path: '/flushing',
    getParentRoute: () => SuperiorValueCreationRoute,
  } as any)
const SuperiorValueCreationLongTermServiceAgreementRoute =
  SuperiorValueCreationLongTermServiceAgreementRouteImport.update({
    id: '/long-term-service-agreement',
    path: '/long-term-service-agreement',
    getParentRoute: () => SuperiorValueCreationRoute,
  } as any)
const SuperiorValueCreationMaintenanceContractsRoute =
  SuperiorValueCreationMaintenanceContractsRouteImport.update({
    id: '/maintenance-contracts',
    path: '/maintenance-contracts',
    getParentRoute: () => SuperiorValueCreationRoute,
  } as any)
const SuperiorValueCreationPressureTestingRoute =
  SuperiorValueCreationPressureTestingRouteImport.update({
    id: '/pressure-testing',
    path: '/pressure-testing',
    getParentRoute: () => SuperiorValueCreationRoute,
  } as any)
const SuperiorValueCreationProductTrainingRoute =
  SuperiorValueCreationProductTrainingRouteImport.update({
    id: '/product-training',
    path: '/product-training',
    getParentRoute: () => SuperiorValueCreationRoute,
  } as any)
const SuperiorValueCreationRefurbishmentsRecertificationRoute =
  SuperiorValueCreationRefurbishmentsRecertificationRouteImport.update({
    id: '/refurbishments-recertification',
    path: '/refurbishments-recertification',
    getParentRoute: () => SuperiorValueCreationRoute,
  } as any)
const SolutionsEngineeredSolutionsIndexRoute =
  SolutionsEngineeredSolutionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SolutionsEngineeredSolutionsRoute,
  } as any)
const SolutionsEngineeredSolutionsDraInjectionSystemsRoute =
  SolutionsEngineeredSolutionsDraInjectionSystemsRouteImport.update({
    id: '/dra-injection-systems',
    path: '/dra-injection-systems',
    getParentRoute: () => SolutionsEngineeredSolutionsRoute,
  } as any)
const SolutionsEngineeredSolutionsHippsSystemsRoute =
  SolutionsEngineeredSolutionsHippsSystemsRouteImport.update({
    id: '/hipps-systems',
    path: '/hipps-systems',
    getParentRoute: () => SolutionsEngineeredSolutionsRoute,
  } as any)
const SolutionsEngineeredSolutionsLubeOilSystemsRoute =
  SolutionsEngineeredSolutionsLubeOilSystemsRouteImport.update({
    id: '/lube-oil-systems',
    path: '/lube-oil-systems',
    getParentRoute: () => SolutionsEngineeredSolutionsRoute,
  } as any)
const SolutionsEngineeredSolutionsMeteringSkidsRoute =
  SolutionsEngineeredSolutionsMeteringSkidsRouteImport.update({
    id: '/metering-skids',
    path: '/metering-skids',
    getParentRoute: () => SolutionsEngineeredSolutionsRoute,
  } as any)
const SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRoute =
  SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRouteImport.update({
    id: '/nitrogen-generator-packages',
    path: '/nitrogen-generator-packages',
    getParentRoute: () => SolutionsEngineeredSolutionsRoute,
  } as any)
const SolutionsEngineeredSolutionsSurgeReliefSkidsRoute =
  SolutionsEngineeredSolutionsSurgeReliefSkidsRouteImport.update({
    id: '/surge-relief-skids',
    path: '/surge-relief-skids',
    getParentRoute: () => SolutionsEngineeredSolutionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/after-market-services': typeof AfterMarketServicesRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/infrastructure': typeof InfrastructureRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/superior-value-creation': typeof SuperiorValueCreationRouteWithChildren
  '/terms': typeof TermsRoute
  '/solutions/chemical-injection-packages': typeof SolutionsChemicalInjectionPackagesRoute
  '/solutions/engineered-solutions': typeof SolutionsEngineeredSolutionsRouteWithChildren
  '/solutions/modular-packages': typeof SolutionsModularPackagesRoute
  '/solutions/wellhead-control-systems': typeof SolutionsWellheadControlSystemsRoute
  '/superior-value-creation/equipment-rental': typeof SuperiorValueCreationEquipmentRentalRoute
  '/superior-value-creation/flushing': typeof SuperiorValueCreationFlushingRoute
  '/superior-value-creation/long-term-service-agreement': typeof SuperiorValueCreationLongTermServiceAgreementRoute
  '/superior-value-creation/maintenance-contracts': typeof SuperiorValueCreationMaintenanceContractsRoute
  '/superior-value-creation/pressure-testing': typeof SuperiorValueCreationPressureTestingRoute
  '/superior-value-creation/product-training': typeof SuperiorValueCreationProductTrainingRoute
  '/superior-value-creation/refurbishments-recertification': typeof SuperiorValueCreationRefurbishmentsRecertificationRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/superior-value-creation/': typeof SuperiorValueCreationIndexRoute
  '/solutions/engineered-solutions/dra-injection-systems': typeof SolutionsEngineeredSolutionsDraInjectionSystemsRoute
  '/solutions/engineered-solutions/hipps-systems': typeof SolutionsEngineeredSolutionsHippsSystemsRoute
  '/solutions/engineered-solutions/lube-oil-systems': typeof SolutionsEngineeredSolutionsLubeOilSystemsRoute
  '/solutions/engineered-solutions/metering-skids': typeof SolutionsEngineeredSolutionsMeteringSkidsRoute
  '/solutions/engineered-solutions/nitrogen-generator-packages': typeof SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRoute
  '/solutions/engineered-solutions/surge-relief-skids': typeof SolutionsEngineeredSolutionsSurgeReliefSkidsRoute
  '/solutions/engineered-solutions/': typeof SolutionsEngineeredSolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/after-market-services': typeof AfterMarketServicesRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/infrastructure': typeof InfrastructureRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/solutions/chemical-injection-packages': typeof SolutionsChemicalInjectionPackagesRoute
  '/solutions/modular-packages': typeof SolutionsModularPackagesRoute
  '/solutions/wellhead-control-systems': typeof SolutionsWellheadControlSystemsRoute
  '/superior-value-creation/equipment-rental': typeof SuperiorValueCreationEquipmentRentalRoute
  '/superior-value-creation/flushing': typeof SuperiorValueCreationFlushingRoute
  '/superior-value-creation/long-term-service-agreement': typeof SuperiorValueCreationLongTermServiceAgreementRoute
  '/superior-value-creation/maintenance-contracts': typeof SuperiorValueCreationMaintenanceContractsRoute
  '/superior-value-creation/pressure-testing': typeof SuperiorValueCreationPressureTestingRoute
  '/superior-value-creation/product-training': typeof SuperiorValueCreationProductTrainingRoute
  '/superior-value-creation/refurbishments-recertification': typeof SuperiorValueCreationRefurbishmentsRecertificationRoute
  '/solutions': typeof SolutionsIndexRoute
  '/superior-value-creation': typeof SuperiorValueCreationIndexRoute
  '/solutions/engineered-solutions/dra-injection-systems': typeof SolutionsEngineeredSolutionsDraInjectionSystemsRoute
  '/solutions/engineered-solutions/hipps-systems': typeof SolutionsEngineeredSolutionsHippsSystemsRoute
  '/solutions/engineered-solutions/lube-oil-systems': typeof SolutionsEngineeredSolutionsLubeOilSystemsRoute
  '/solutions/engineered-solutions/metering-skids': typeof SolutionsEngineeredSolutionsMeteringSkidsRoute
  '/solutions/engineered-solutions/nitrogen-generator-packages': typeof SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRoute
  '/solutions/engineered-solutions/surge-relief-skids': typeof SolutionsEngineeredSolutionsSurgeReliefSkidsRoute
  '/solutions/engineered-solutions': typeof SolutionsEngineeredSolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/after-market-services': typeof AfterMarketServicesRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/infrastructure': typeof InfrastructureRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/superior-value-creation': typeof SuperiorValueCreationRouteWithChildren
  '/terms': typeof TermsRoute
  '/solutions/chemical-injection-packages': typeof SolutionsChemicalInjectionPackagesRoute
  '/solutions/engineered-solutions': typeof SolutionsEngineeredSolutionsRouteWithChildren
  '/solutions/modular-packages': typeof SolutionsModularPackagesRoute
  '/solutions/wellhead-control-systems': typeof SolutionsWellheadControlSystemsRoute
  '/superior-value-creation/equipment-rental': typeof SuperiorValueCreationEquipmentRentalRoute
  '/superior-value-creation/flushing': typeof SuperiorValueCreationFlushingRoute
  '/superior-value-creation/long-term-service-agreement': typeof SuperiorValueCreationLongTermServiceAgreementRoute
  '/superior-value-creation/maintenance-contracts': typeof SuperiorValueCreationMaintenanceContractsRoute
  '/superior-value-creation/pressure-testing': typeof SuperiorValueCreationPressureTestingRoute
  '/superior-value-creation/product-training': typeof SuperiorValueCreationProductTrainingRoute
  '/superior-value-creation/refurbishments-recertification': typeof SuperiorValueCreationRefurbishmentsRecertificationRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/superior-value-creation/': typeof SuperiorValueCreationIndexRoute
  '/solutions/engineered-solutions/dra-injection-systems': typeof SolutionsEngineeredSolutionsDraInjectionSystemsRoute
  '/solutions/engineered-solutions/hipps-systems': typeof SolutionsEngineeredSolutionsHippsSystemsRoute
  '/solutions/engineered-solutions/lube-oil-systems': typeof SolutionsEngineeredSolutionsLubeOilSystemsRoute
  '/solutions/engineered-solutions/metering-skids': typeof SolutionsEngineeredSolutionsMeteringSkidsRoute
  '/solutions/engineered-solutions/nitrogen-generator-packages': typeof SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRoute
  '/solutions/engineered-solutions/surge-relief-skids': typeof SolutionsEngineeredSolutionsSurgeReliefSkidsRoute
  '/solutions/engineered-solutions/': typeof SolutionsEngineeredSolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/after-market-services'
    | '/careers'
    | '/contact'
    | '/industries'
    | '/infrastructure'
    | '/privacy-policy'
    | '/superior-value-creation'
    | '/terms'
    | '/solutions/chemical-injection-packages'
    | '/solutions/engineered-solutions'
    | '/solutions/modular-packages'
    | '/solutions/wellhead-control-systems'
    | '/superior-value-creation/equipment-rental'
    | '/superior-value-creation/flushing'
    | '/superior-value-creation/long-term-service-agreement'
    | '/superior-value-creation/maintenance-contracts'
    | '/superior-value-creation/pressure-testing'
    | '/superior-value-creation/product-training'
    | '/superior-value-creation/refurbishments-recertification'
    | '/solutions/'
    | '/superior-value-creation/'
    | '/solutions/engineered-solutions/dra-injection-systems'
    | '/solutions/engineered-solutions/hipps-systems'
    | '/solutions/engineered-solutions/lube-oil-systems'
    | '/solutions/engineered-solutions/metering-skids'
    | '/solutions/engineered-solutions/nitrogen-generator-packages'
    | '/solutions/engineered-solutions/surge-relief-skids'
    | '/solutions/engineered-solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/after-market-services'
    | '/careers'
    | '/contact'
    | '/industries'
    | '/infrastructure'
    | '/privacy-policy'
    | '/terms'
    | '/solutions/chemical-injection-packages'
    | '/solutions/modular-packages'
    | '/solutions/wellhead-control-systems'
    | '/superior-value-creation/equipment-rental'
    | '/superior-value-creation/flushing'
    | '/superior-value-creation/long-term-service-agreement'
    | '/superior-value-creation/maintenance-contracts'
    | '/superior-value-creation/pressure-testing'
    | '/superior-value-creation/product-training'
    | '/superior-value-creation/refurbishments-recertification'
    | '/solutions'
    | '/superior-value-creation'
    | '/solutions/engineered-solutions/dra-injection-systems'
    | '/solutions/engineered-solutions/hipps-systems'
    | '/solutions/engineered-solutions/lube-oil-systems'
    | '/solutions/engineered-solutions/metering-skids'
    | '/solutions/engineered-solutions/nitrogen-generator-packages'
    | '/solutions/engineered-solutions/surge-relief-skids'
    | '/solutions/engineered-solutions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/after-market-services'
    | '/careers'
    | '/contact'
    | '/industries'
    | '/infrastructure'
    | '/privacy-policy'
    | '/superior-value-creation'
    | '/terms'
    | '/solutions/chemical-injection-packages'
    | '/solutions/engineered-solutions'
    | '/solutions/modular-packages'
    | '/solutions/wellhead-control-systems'
    | '/superior-value-creation/equipment-rental'
    | '/superior-value-creation/flushing'
    | '/superior-value-creation/long-term-service-agreement'
    | '/superior-value-creation/maintenance-contracts'
    | '/superior-value-creation/pressure-testing'
    | '/superior-value-creation/product-training'
    | '/superior-value-creation/refurbishments-recertification'
    | '/solutions/'
    | '/superior-value-creation/'
    | '/solutions/engineered-solutions/dra-injection-systems'
    | '/solutions/engineered-solutions/hipps-systems'
    | '/solutions/engineered-solutions/lube-oil-systems'
    | '/solutions/engineered-solutions/metering-skids'
    | '/solutions/engineered-solutions/nitrogen-generator-packages'
    | '/solutions/engineered-solutions/surge-relief-skids'
    | '/solutions/engineered-solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AfterMarketServicesRoute: typeof AfterMarketServicesRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  InfrastructureRoute: typeof InfrastructureRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SuperiorValueCreationRoute: typeof SuperiorValueCreationRouteWithChildren
  TermsRoute: typeof TermsRoute
  SolutionsChemicalInjectionPackagesRoute: typeof SolutionsChemicalInjectionPackagesRoute
  SolutionsEngineeredSolutionsRoute: typeof SolutionsEngineeredSolutionsRouteWithChildren
  SolutionsModularPackagesRoute: typeof SolutionsModularPackagesRoute
  SolutionsWellheadControlSystemsRoute: typeof SolutionsWellheadControlSystemsRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/after-market-services': {
      id: '/after-market-services'
      path: '/after-market-services'
      fullPath: '/after-market-services'
      preLoaderRoute: typeof AfterMarketServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superior-value-creation': {
      id: '/superior-value-creation'
      path: '/superior-value-creation'
      fullPath: '/superior-value-creation'
      preLoaderRoute: typeof SuperiorValueCreationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/chemical-injection-packages': {
      id: '/solutions/chemical-injection-packages'
      path: '/solutions/chemical-injection-packages'
      fullPath: '/solutions/chemical-injection-packages'
      preLoaderRoute: typeof SolutionsChemicalInjectionPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/engineered-solutions': {
      id: '/solutions/engineered-solutions'
      path: '/solutions/engineered-solutions'
      fullPath: '/solutions/engineered-solutions'
      preLoaderRoute: typeof SolutionsEngineeredSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/modular-packages': {
      id: '/solutions/modular-packages'
      path: '/solutions/modular-packages'
      fullPath: '/solutions/modular-packages'
      preLoaderRoute: typeof SolutionsModularPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/wellhead-control-systems': {
      id: '/solutions/wellhead-control-systems'
      path: '/solutions/wellhead-control-systems'
      fullPath: '/solutions/wellhead-control-systems'
      preLoaderRoute: typeof SolutionsWellheadControlSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superior-value-creation/': {
      id: '/superior-value-creation/'
      path: '/'
      fullPath: '/superior-value-creation/'
      preLoaderRoute: typeof SuperiorValueCreationIndexRouteImport
      parentRoute: typeof SuperiorValueCreationRoute
    }
    '/superior-value-creation/equipment-rental': {
      id: '/superior-value-creation/equipment-rental'
      path: '/equipment-rental'
      fullPath: '/superior-value-creation/equipment-rental'
      preLoaderRoute: typeof SuperiorValueCreationEquipmentRentalRouteImport
      parentRoute: typeof SuperiorValueCreationRoute
    }
    '/superior-value-creation/flushing': {
      id: '/superior-value-creation/flushing'
      path: '/flushing'
      fullPath: '/superior-value-creation/flushing'
      preLoaderRoute: typeof SuperiorValueCreationFlushingRouteImport
      parentRoute: typeof SuperiorValueCreationRoute
    }
    '/superior-value-creation/long-term-service-agreement': {
      id: '/superior-value-creation/long-term-service-agreement'
      path: '/long-term-service-agreement'
      fullPath: '/superior-value-creation/long-term-service-agreement'
      preLoaderRoute: typeof SuperiorValueCreationLongTermServiceAgreementRouteImport
      parentRoute: typeof SuperiorValueCreationRoute
    }
    '/superior-value-creation/maintenance-contracts': {
      id: '/superior-value-creation/maintenance-contracts'
      path: '/maintenance-contracts'
      fullPath: '/superior-value-creation/maintenance-contracts'
      preLoaderRoute: typeof SuperiorValueCreationMaintenanceContractsRouteImport
      parentRoute: typeof SuperiorValueCreationRoute
    }
    '/superior-value-creation/pressure-testing': {
      id: '/superior-value-creation/pressure-testing'
      path: '/pressure-testing'
      fullPath: '/superior-value-creation/pressure-testing'
      preLoaderRoute: typeof SuperiorValueCreationPressureTestingRouteImport
      parentRoute: typeof SuperiorValueCreationRoute
    }
    '/superior-value-creation/product-training': {
      id: '/superior-value-creation/product-training'
      path: '/product-training'
      fullPath: '/superior-value-creation/product-training'
      preLoaderRoute: typeof SuperiorValueCreationProductTrainingRouteImport
      parentRoute: typeof SuperiorValueCreationRoute
    }
    '/superior-value-creation/refurbishments-recertification': {
      id: '/superior-value-creation/refurbishments-recertification'
      path: '/refurbishments-recertification'
      fullPath: '/superior-value-creation/refurbishments-recertification'
      preLoaderRoute: typeof SuperiorValueCreationRefurbishmentsRecertificationRouteImport
      parentRoute: typeof SuperiorValueCreationRoute
    }
    '/solutions/engineered-solutions/': {
      id: '/solutions/engineered-solutions/'
      path: '/'
      fullPath: '/solutions/engineered-solutions/'
      preLoaderRoute: typeof SolutionsEngineeredSolutionsIndexRouteImport
      parentRoute: typeof SolutionsEngineeredSolutionsRoute
    }
    '/solutions/engineered-solutions/dra-injection-systems': {
      id: '/solutions/engineered-solutions/dra-injection-systems'
      path: '/dra-injection-systems'
      fullPath: '/solutions/engineered-solutions/dra-injection-systems'
      preLoaderRoute: typeof SolutionsEngineeredSolutionsDraInjectionSystemsRouteImport
      parentRoute: typeof SolutionsEngineeredSolutionsRoute
    }
    '/solutions/engineered-solutions/hipps-systems': {
      id: '/solutions/engineered-solutions/hipps-systems'
      path: '/hipps-systems'
      fullPath: '/solutions/engineered-solutions/hipps-systems'
      preLoaderRoute: typeof SolutionsEngineeredSolutionsHippsSystemsRouteImport
      parentRoute: typeof SolutionsEngineeredSolutionsRoute
    }
    '/solutions/engineered-solutions/lube-oil-systems': {
      id: '/solutions/engineered-solutions/lube-oil-systems'
      path: '/lube-oil-systems'
      fullPath: '/solutions/engineered-solutions/lube-oil-systems'
      preLoaderRoute: typeof SolutionsEngineeredSolutionsLubeOilSystemsRouteImport
      parentRoute: typeof SolutionsEngineeredSolutionsRoute
    }
    '/solutions/engineered-solutions/metering-skids': {
      id: '/solutions/engineered-solutions/metering-skids'
      path: '/metering-skids'
      fullPath: '/solutions/engineered-solutions/metering-skids'
      preLoaderRoute: typeof SolutionsEngineeredSolutionsMeteringSkidsRouteImport
      parentRoute: typeof SolutionsEngineeredSolutionsRoute
    }
    '/solutions/engineered-solutions/nitrogen-generator-packages': {
      id: '/solutions/engineered-solutions/nitrogen-generator-packages'
      path: '/nitrogen-generator-packages'
      fullPath: '/solutions/engineered-solutions/nitrogen-generator-packages'
      preLoaderRoute: typeof SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRouteImport
      parentRoute: typeof SolutionsEngineeredSolutionsRoute
    }
    '/solutions/engineered-solutions/surge-relief-skids': {
      id: '/solutions/engineered-solutions/surge-relief-skids'
      path: '/surge-relief-skids'
      fullPath: '/solutions/engineered-solutions/surge-relief-skids'
      preLoaderRoute: typeof SolutionsEngineeredSolutionsSurgeReliefSkidsRouteImport
      parentRoute: typeof SolutionsEngineeredSolutionsRoute
    }
  }
}

interface SuperiorValueCreationRouteChildren {
  SuperiorValueCreationEquipmentRentalRoute: typeof SuperiorValueCreationEquipmentRentalRoute
  SuperiorValueCreationFlushingRoute: typeof SuperiorValueCreationFlushingRoute
  SuperiorValueCreationLongTermServiceAgreementRoute: typeof SuperiorValueCreationLongTermServiceAgreementRoute
  SuperiorValueCreationMaintenanceContractsRoute: typeof SuperiorValueCreationMaintenanceContractsRoute
  SuperiorValueCreationPressureTestingRoute: typeof SuperiorValueCreationPressureTestingRoute
  SuperiorValueCreationProductTrainingRoute: typeof SuperiorValueCreationProductTrainingRoute
  SuperiorValueCreationRefurbishmentsRecertificationRoute: typeof SuperiorValueCreationRefurbishmentsRecertificationRoute
  SuperiorValueCreationIndexRoute: typeof SuperiorValueCreationIndexRoute
}

const SuperiorValueCreationRouteChildren: SuperiorValueCreationRouteChildren = {
  SuperiorValueCreationEquipmentRentalRoute:
    SuperiorValueCreationEquipmentRentalRoute,
  SuperiorValueCreationFlushingRoute: SuperiorValueCreationFlushingRoute,
  SuperiorValueCreationLongTermServiceAgreementRoute:
    SuperiorValueCreationLongTermServiceAgreementRoute,
  SuperiorValueCreationMaintenanceContractsRoute:
    SuperiorValueCreationMaintenanceContractsRoute,
  SuperiorValueCreationPressureTestingRoute:
    SuperiorValueCreationPressureTestingRoute,
  SuperiorValueCreationProductTrainingRoute:
    SuperiorValueCreationProductTrainingRoute,
  SuperiorValueCreationRefurbishmentsRecertificationRoute:
    SuperiorValueCreationRefurbishmentsRecertificationRoute,
  SuperiorValueCreationIndexRoute: SuperiorValueCreationIndexRoute,
}

const SuperiorValueCreationRouteWithChildren =
  SuperiorValueCreationRoute._addFileChildren(
    SuperiorValueCreationRouteChildren,
  )

interface SolutionsEngineeredSolutionsRouteChildren {
  SolutionsEngineeredSolutionsDraInjectionSystemsRoute: typeof SolutionsEngineeredSolutionsDraInjectionSystemsRoute
  SolutionsEngineeredSolutionsHippsSystemsRoute: typeof SolutionsEngineeredSolutionsHippsSystemsRoute
  SolutionsEngineeredSolutionsLubeOilSystemsRoute: typeof SolutionsEngineeredSolutionsLubeOilSystemsRoute
  SolutionsEngineeredSolutionsMeteringSkidsRoute: typeof SolutionsEngineeredSolutionsMeteringSkidsRoute
  SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRoute: typeof SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRoute
  SolutionsEngineeredSolutionsSurgeReliefSkidsRoute: typeof SolutionsEngineeredSolutionsSurgeReliefSkidsRoute
  SolutionsEngineeredSolutionsIndexRoute: typeof SolutionsEngineeredSolutionsIndexRoute
}

const SolutionsEngineeredSolutionsRouteChildren: SolutionsEngineeredSolutionsRouteChildren =
  {
    SolutionsEngineeredSolutionsDraInjectionSystemsRoute:
      SolutionsEngineeredSolutionsDraInjectionSystemsRoute,
    SolutionsEngineeredSolutionsHippsSystemsRoute:
      SolutionsEngineeredSolutionsHippsSystemsRoute,
    SolutionsEngineeredSolutionsLubeOilSystemsRoute:
      SolutionsEngineeredSolutionsLubeOilSystemsRoute,
    SolutionsEngineeredSolutionsMeteringSkidsRoute:
      SolutionsEngineeredSolutionsMeteringSkidsRoute,
    SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRoute:
      SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRoute,
    SolutionsEngineeredSolutionsSurgeReliefSkidsRoute:
      SolutionsEngineeredSolutionsSurgeReliefSkidsRoute,
    SolutionsEngineeredSolutionsIndexRoute:
      SolutionsEngineeredSolutionsIndexRoute,
  }

const SolutionsEngineeredSolutionsRouteWithChildren =
  SolutionsEngineeredSolutionsRoute._addFileChildren(
    SolutionsEngineeredSolutionsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AfterMarketServicesRoute: AfterMarketServicesRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  InfrastructureRoute: InfrastructureRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SuperiorValueCreationRoute: SuperiorValueCreationRouteWithChildren,
  TermsRoute: TermsRoute,
  SolutionsChemicalInjectionPackagesRoute:
    SolutionsChemicalInjectionPackagesRoute,
  SolutionsEngineeredSolutionsRoute:
    SolutionsEngineeredSolutionsRouteWithChildren,
  SolutionsModularPackagesRoute: SolutionsModularPackagesRoute,
  SolutionsWellheadControlSystemsRoute: SolutionsWellheadControlSystemsRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
