/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FacilityRouteImport } from './routes/facility'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsChemicalInjectionPackagesRouteImport } from './routes/solutions.chemical-injection-packages'
import { Route as SolutionsEngineeredSolutionsRouteImport } from './routes/solutions.engineered-solutions'
import { Route as SolutionsModularPackagesRouteImport } from './routes/solutions.modular-packages'
import { Route as SolutionsWellheadControlSystemsRouteImport } from './routes/solutions.wellhead-control-systems'
import { Route as SolutionsEngineeredSolutionsDraInjectionSystemsRouteImport } from './routes/solutions.engineered-solutions.dra-injection-systems'
import { Route as SolutionsEngineeredSolutionsHippsSystemsRouteImport } from './routes/solutions.engineered-solutions.hipps-systems'
import { Route as SolutionsEngineeredSolutionsLubeOilSystemsRouteImport } from './routes/solutions.engineered-solutions.lube-oil-systems'
import { Route as SolutionsEngineeredSolutionsMeteringSkidsRouteImport } from './routes/solutions.engineered-solutions.metering-skids'
import { Route as SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRouteImport } from './routes/solutions.engineered-solutions.nitrogen-generator-packages'
import { Route as SolutionsEngineeredSolutionsSurgeReliefSkidsRouteImport } from './routes/solutions.engineered-solutions.surge-relief-skids'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityRoute = FacilityRouteImport.update({
  id: '/facility',
  path: '/facility',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsChemicalInjectionPackagesRoute =
  SolutionsChemicalInjectionPackagesRouteImport.update({
    id: '/solutions/chemical-injection-packages',
    path: '/solutions/chemical-injection-packages',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsEngineeredSolutionsRoute =
  SolutionsEngineeredSolutionsRouteImport.update({
    id: '/solutions/engineered-solutions',
    path: '/solutions/engineered-solutions',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsModularPackagesRoute =
  SolutionsModularPackagesRouteImport.update({
    id: '/solutions/modular-packages',
    path: '/solutions/modular-packages',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsWellheadControlSystemsRoute =
  SolutionsWellheadControlSystemsRouteImport.update({
    id: '/solutions/wellhead-control-systems',
    path: '/solutions/wellhead-control-systems',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsEngineeredSolutionsDraInjectionSystemsRoute =
  SolutionsEngineeredSolutionsDraInjectionSystemsRouteImport.update({
    id: '/dra-injection-systems',
    path: '/dra-injection-systems',
    getParentRoute: () => SolutionsEngineeredSolutionsRoute,
  } as any)
const SolutionsEngineeredSolutionsHippsSystemsRoute =
  SolutionsEngineeredSolutionsHippsSystemsRouteImport.update({
    id: '/hipps-systems',
    path: '/hipps-systems',
    getParentRoute: () => SolutionsEngineeredSolutionsRoute,
  } as any)
const SolutionsEngineeredSolutionsLubeOilSystemsRoute =
  SolutionsEngineeredSolutionsLubeOilSystemsRouteImport.update({
    id: '/lube-oil-systems',
    path: '/lube-oil-systems',
    getParentRoute: () => SolutionsEngineeredSolutionsRoute,
  } as any)
const SolutionsEngineeredSolutionsMeteringSkidsRoute =
  SolutionsEngineeredSolutionsMeteringSkidsRouteImport.update({
    id: '/metering-skids',
    path: '/metering-skids',
    getParentRoute: () => SolutionsEngineeredSolutionsRoute,
  } as any)
const SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRoute =
  SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRouteImport.update({
    id: '/nitrogen-generator-packages',
    path: '/nitrogen-generator-packages',
    getParentRoute: () => SolutionsEngineeredSolutionsRoute,
  } as any)
const SolutionsEngineeredSolutionsSurgeReliefSkidsRoute =
  SolutionsEngineeredSolutionsSurgeReliefSkidsRouteImport.update({
    id: '/surge-relief-skids',
    path: '/surge-relief-skids',
    getParentRoute: () => SolutionsEngineeredSolutionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/facility': typeof FacilityRoute
  '/industries': typeof IndustriesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/solutions/chemical-injection-packages': typeof SolutionsChemicalInjectionPackagesRoute
  '/solutions/engineered-solutions': typeof SolutionsEngineeredSolutionsRouteWithChildren
  '/solutions/modular-packages': typeof SolutionsModularPackagesRoute
  '/solutions/wellhead-control-systems': typeof SolutionsWellheadControlSystemsRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/solutions/engineered-solutions/dra-injection-systems': typeof SolutionsEngineeredSolutionsDraInjectionSystemsRoute
  '/solutions/engineered-solutions/hipps-systems': typeof SolutionsEngineeredSolutionsHippsSystemsRoute
  '/solutions/engineered-solutions/lube-oil-systems': typeof SolutionsEngineeredSolutionsLubeOilSystemsRoute
  '/solutions/engineered-solutions/metering-skids': typeof SolutionsEngineeredSolutionsMeteringSkidsRoute
  '/solutions/engineered-solutions/nitrogen-generator-packages': typeof SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRoute
  '/solutions/engineered-solutions/surge-relief-skids': typeof SolutionsEngineeredSolutionsSurgeReliefSkidsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/facility': typeof FacilityRoute
  '/industries': typeof IndustriesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/solutions/chemical-injection-packages': typeof SolutionsChemicalInjectionPackagesRoute
  '/solutions/engineered-solutions': typeof SolutionsEngineeredSolutionsRouteWithChildren
  '/solutions/modular-packages': typeof SolutionsModularPackagesRoute
  '/solutions/wellhead-control-systems': typeof SolutionsWellheadControlSystemsRoute
  '/solutions': typeof SolutionsIndexRoute
  '/solutions/engineered-solutions/dra-injection-systems': typeof SolutionsEngineeredSolutionsDraInjectionSystemsRoute
  '/solutions/engineered-solutions/hipps-systems': typeof SolutionsEngineeredSolutionsHippsSystemsRoute
  '/solutions/engineered-solutions/lube-oil-systems': typeof SolutionsEngineeredSolutionsLubeOilSystemsRoute
  '/solutions/engineered-solutions/metering-skids': typeof SolutionsEngineeredSolutionsMeteringSkidsRoute
  '/solutions/engineered-solutions/nitrogen-generator-packages': typeof SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRoute
  '/solutions/engineered-solutions/surge-relief-skids': typeof SolutionsEngineeredSolutionsSurgeReliefSkidsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/facility': typeof FacilityRoute
  '/industries': typeof IndustriesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/solutions/chemical-injection-packages': typeof SolutionsChemicalInjectionPackagesRoute
  '/solutions/engineered-solutions': typeof SolutionsEngineeredSolutionsRouteWithChildren
  '/solutions/modular-packages': typeof SolutionsModularPackagesRoute
  '/solutions/wellhead-control-systems': typeof SolutionsWellheadControlSystemsRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/solutions/engineered-solutions/dra-injection-systems': typeof SolutionsEngineeredSolutionsDraInjectionSystemsRoute
  '/solutions/engineered-solutions/hipps-systems': typeof SolutionsEngineeredSolutionsHippsSystemsRoute
  '/solutions/engineered-solutions/lube-oil-systems': typeof SolutionsEngineeredSolutionsLubeOilSystemsRoute
  '/solutions/engineered-solutions/metering-skids': typeof SolutionsEngineeredSolutionsMeteringSkidsRoute
  '/solutions/engineered-solutions/nitrogen-generator-packages': typeof SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRoute
  '/solutions/engineered-solutions/surge-relief-skids': typeof SolutionsEngineeredSolutionsSurgeReliefSkidsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/facility'
    | '/industries'
    | '/privacy-policy'
    | '/projects'
    | '/services'
    | '/terms'
    | '/solutions/chemical-injection-packages'
    | '/solutions/engineered-solutions'
    | '/solutions/modular-packages'
    | '/solutions/wellhead-control-systems'
    | '/solutions/'
    | '/solutions/engineered-solutions/dra-injection-systems'
    | '/solutions/engineered-solutions/hipps-systems'
    | '/solutions/engineered-solutions/lube-oil-systems'
    | '/solutions/engineered-solutions/metering-skids'
    | '/solutions/engineered-solutions/nitrogen-generator-packages'
    | '/solutions/engineered-solutions/surge-relief-skids'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/facility'
    | '/industries'
    | '/privacy-policy'
    | '/projects'
    | '/services'
    | '/terms'
    | '/solutions/chemical-injection-packages'
    | '/solutions/engineered-solutions'
    | '/solutions/modular-packages'
    | '/solutions/wellhead-control-systems'
    | '/solutions'
    | '/solutions/engineered-solutions/dra-injection-systems'
    | '/solutions/engineered-solutions/hipps-systems'
    | '/solutions/engineered-solutions/lube-oil-systems'
    | '/solutions/engineered-solutions/metering-skids'
    | '/solutions/engineered-solutions/nitrogen-generator-packages'
    | '/solutions/engineered-solutions/surge-relief-skids'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/facility'
    | '/industries'
    | '/privacy-policy'
    | '/projects'
    | '/services'
    | '/terms'
    | '/solutions/chemical-injection-packages'
    | '/solutions/engineered-solutions'
    | '/solutions/modular-packages'
    | '/solutions/wellhead-control-systems'
    | '/solutions/'
    | '/solutions/engineered-solutions/dra-injection-systems'
    | '/solutions/engineered-solutions/hipps-systems'
    | '/solutions/engineered-solutions/lube-oil-systems'
    | '/solutions/engineered-solutions/metering-skids'
    | '/solutions/engineered-solutions/nitrogen-generator-packages'
    | '/solutions/engineered-solutions/surge-relief-skids'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FacilityRoute: typeof FacilityRoute
  IndustriesRoute: typeof IndustriesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  SolutionsChemicalInjectionPackagesRoute: typeof SolutionsChemicalInjectionPackagesRoute
  SolutionsEngineeredSolutionsRoute: typeof SolutionsEngineeredSolutionsRouteWithChildren
  SolutionsModularPackagesRoute: typeof SolutionsModularPackagesRoute
  SolutionsWellheadControlSystemsRoute: typeof SolutionsWellheadControlSystemsRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility': {
      id: '/facility'
      path: '/facility'
      fullPath: '/facility'
      preLoaderRoute: typeof FacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/chemical-injection-packages': {
      id: '/solutions/chemical-injection-packages'
      path: '/solutions/chemical-injection-packages'
      fullPath: '/solutions/chemical-injection-packages'
      preLoaderRoute: typeof SolutionsChemicalInjectionPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/engineered-solutions': {
      id: '/solutions/engineered-solutions'
      path: '/solutions/engineered-solutions'
      fullPath: '/solutions/engineered-solutions'
      preLoaderRoute: typeof SolutionsEngineeredSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/modular-packages': {
      id: '/solutions/modular-packages'
      path: '/solutions/modular-packages'
      fullPath: '/solutions/modular-packages'
      preLoaderRoute: typeof SolutionsModularPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/wellhead-control-systems': {
      id: '/solutions/wellhead-control-systems'
      path: '/solutions/wellhead-control-systems'
      fullPath: '/solutions/wellhead-control-systems'
      preLoaderRoute: typeof SolutionsWellheadControlSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/engineered-solutions/dra-injection-systems': {
      id: '/solutions/engineered-solutions/dra-injection-systems'
      path: '/dra-injection-systems'
      fullPath: '/solutions/engineered-solutions/dra-injection-systems'
      preLoaderRoute: typeof SolutionsEngineeredSolutionsDraInjectionSystemsRouteImport
      parentRoute: typeof SolutionsEngineeredSolutionsRoute
    }
    '/solutions/engineered-solutions/hipps-systems': {
      id: '/solutions/engineered-solutions/hipps-systems'
      path: '/hipps-systems'
      fullPath: '/solutions/engineered-solutions/hipps-systems'
      preLoaderRoute: typeof SolutionsEngineeredSolutionsHippsSystemsRouteImport
      parentRoute: typeof SolutionsEngineeredSolutionsRoute
    }
    '/solutions/engineered-solutions/lube-oil-systems': {
      id: '/solutions/engineered-solutions/lube-oil-systems'
      path: '/lube-oil-systems'
      fullPath: '/solutions/engineered-solutions/lube-oil-systems'
      preLoaderRoute: typeof SolutionsEngineeredSolutionsLubeOilSystemsRouteImport
      parentRoute: typeof SolutionsEngineeredSolutionsRoute
    }
    '/solutions/engineered-solutions/metering-skids': {
      id: '/solutions/engineered-solutions/metering-skids'
      path: '/metering-skids'
      fullPath: '/solutions/engineered-solutions/metering-skids'
      preLoaderRoute: typeof SolutionsEngineeredSolutionsMeteringSkidsRouteImport
      parentRoute: typeof SolutionsEngineeredSolutionsRoute
    }
    '/solutions/engineered-solutions/nitrogen-generator-packages': {
      id: '/solutions/engineered-solutions/nitrogen-generator-packages'
      path: '/nitrogen-generator-packages'
      fullPath: '/solutions/engineered-solutions/nitrogen-generator-packages'
      preLoaderRoute: typeof SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRouteImport
      parentRoute: typeof SolutionsEngineeredSolutionsRoute
    }
    '/solutions/engineered-solutions/surge-relief-skids': {
      id: '/solutions/engineered-solutions/surge-relief-skids'
      path: '/surge-relief-skids'
      fullPath: '/solutions/engineered-solutions/surge-relief-skids'
      preLoaderRoute: typeof SolutionsEngineeredSolutionsSurgeReliefSkidsRouteImport
      parentRoute: typeof SolutionsEngineeredSolutionsRoute
    }
  }
}

interface SolutionsEngineeredSolutionsRouteChildren {
  SolutionsEngineeredSolutionsDraInjectionSystemsRoute: typeof SolutionsEngineeredSolutionsDraInjectionSystemsRoute
  SolutionsEngineeredSolutionsHippsSystemsRoute: typeof SolutionsEngineeredSolutionsHippsSystemsRoute
  SolutionsEngineeredSolutionsLubeOilSystemsRoute: typeof SolutionsEngineeredSolutionsLubeOilSystemsRoute
  SolutionsEngineeredSolutionsMeteringSkidsRoute: typeof SolutionsEngineeredSolutionsMeteringSkidsRoute
  SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRoute: typeof SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRoute
  SolutionsEngineeredSolutionsSurgeReliefSkidsRoute: typeof SolutionsEngineeredSolutionsSurgeReliefSkidsRoute
}

const SolutionsEngineeredSolutionsRouteChildren: SolutionsEngineeredSolutionsRouteChildren =
  {
    SolutionsEngineeredSolutionsDraInjectionSystemsRoute:
      SolutionsEngineeredSolutionsDraInjectionSystemsRoute,
    SolutionsEngineeredSolutionsHippsSystemsRoute:
      SolutionsEngineeredSolutionsHippsSystemsRoute,
    SolutionsEngineeredSolutionsLubeOilSystemsRoute:
      SolutionsEngineeredSolutionsLubeOilSystemsRoute,
    SolutionsEngineeredSolutionsMeteringSkidsRoute:
      SolutionsEngineeredSolutionsMeteringSkidsRoute,
    SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRoute:
      SolutionsEngineeredSolutionsNitrogenGeneratorPackagesRoute,
    SolutionsEngineeredSolutionsSurgeReliefSkidsRoute:
      SolutionsEngineeredSolutionsSurgeReliefSkidsRoute,
  }

const SolutionsEngineeredSolutionsRouteWithChildren =
  SolutionsEngineeredSolutionsRoute._addFileChildren(
    SolutionsEngineeredSolutionsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FacilityRoute: FacilityRoute,
  IndustriesRoute: IndustriesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  SolutionsChemicalInjectionPackagesRoute:
    SolutionsChemicalInjectionPackagesRoute,
  SolutionsEngineeredSolutionsRoute:
    SolutionsEngineeredSolutionsRouteWithChildren,
  SolutionsModularPackagesRoute: SolutionsModularPackagesRoute,
  SolutionsWellheadControlSystemsRoute: SolutionsWellheadControlSystemsRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
